/*INSERT INTO DEVELOPER (DEV_NAME) VALUES ('Jana');--1
INSERT INTO DEVELOPER (DEV_NAME) VALUES ('Marco');--2
INSERT INTO DEVELOPER (DEV_NAME) VALUES ('Marcin');--3
INSERT INTO DEVELOPER (DEV_NAME) VALUES ('Raiko');--4
INSERT INTO DEVELOPER (DEV_NAME) VALUES ('Pavel');--5
INSERT INTO DEVELOPER (DEV_NAME) VALUES ('Sukhmeet');--6
INSERT INTO DEVELOPER (DEV_NAME) VALUES ('Daniel');--7
INSERT INTO DEVELOPER (DEV_NAME) VALUES ('Alex');--8
INSERT INTO DEVELOPER (DEV_NAME) VALUES ('Benjamin Benz');--9
INSERT INTO DEVELOPER (DEV_NAME) VALUES ('Benjamin Bohlmann');--10

INSERT INTO RESTAURANT (RES_NAME) VALUES ('Mela');--1
INSERT INTO RESTAURANT (RES_NAME) VALUES ('German place');--2
INSERT INTO RESTAURANT (RES_NAME) VALUES ('Burger place');--3
INSERT INTO RESTAURANT (RES_NAME) VALUES ('Buddhahaus');--4
INSERT INTO RESTAURANT (RES_NAME) VALUES ('Mexican restaurant');--5
INSERT INTO RESTAURANT (RES_NAME) VALUES ('Pizza');--6
INSERT INTO RESTAURANT (RES_NAME) VALUES ('Turkish place');--7
INSERT INTO RESTAURANT (RES_NAME) VALUES ('Papaya');--8
INSERT INTO RESTAURANT (RES_NAME) VALUES ('Vietnamese');--9

-- Jana
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (1, 1);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (1, 2);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (1, 3);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (1, 4);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (1, 5);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (1, 6);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (1, 7);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (1, 8);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID, LIK_VALUE) VALUES (1, 9, -1);
-- Marco
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (2, 1);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (2, 2);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (2, 3);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (2, 4);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (2, 5);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID, LIK_VALUE) VALUES (2, 6, -1);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (2, 7);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (2, 8);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (2, 9);
-- Marcin
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (3, 1);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (3, 2);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (3, 3);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (3, 4);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (3, 5);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (3, 6);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (3, 7);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (3, 8);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (3, 9);
-- Raiko
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (4, 1);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (4, 2);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (4, 3);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (4, 4);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (4, 5);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (4, 6);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (4, 7);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (4, 8);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (4, 9);
-- Pavel
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (5, 1);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (5, 2);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (5, 3);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (5, 4);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (5, 5);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (5, 6);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (5, 7);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (5, 8);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID, LIK_VALUE) VALUES (5, 9, -1);
-- Sukhmeet
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (6, 1);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID, LIK_VALUE) VALUES (6, 2, -1);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID, LIK_VALUE) VALUES (6, 3, -1);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID, LIK_VALUE) VALUES (6, 4, -1);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (6, 5);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (6, 6);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (6, 7);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (6, 8);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (6, 9);
-- Daniel
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (7, 1);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (7, 2);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (7, 3);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (7, 4);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (7, 5);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (7, 6);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (7, 7);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (7, 8);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (7, 9);
-- Alex
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (8, 1);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (8, 2);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (8, 3);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (8, 4);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (8, 5);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (8, 6);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (8, 7);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (8, 8);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (8, 9);
-- Benjamin Benz
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (9, 1);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (9, 2);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (9, 3);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (9, 4);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (9, 5);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (9, 6);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (9, 7);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (9, 8);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (9, 9);
-- Benjamin Bohlmann
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (10, 1);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (10, 2);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (10, 3);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (10, 4);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (10, 5);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (10, 6);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (10, 7);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (10, 8);
INSERT INTO LIKING (LIK_DEV_ID, LIK_RES_ID) VALUES (10, 9);
*/